name = "Fabric Modpack"
author = "Laen111"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "55ccbb0d2d94f957d52e0ddf63a143496e275a94201f0064d8b7ae5c7545c193"

[versions]
fabric = "0.14.7"
minecraft = "1.19"

[options]
acceptable-game-versions = ["1.18.2", "1.19"]
