name = "Fabric Modpack"
author = "Laen111"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "86ef7c97e79de4425dae08fe87a4b8cad3c9a6018eb7528e8af93275596655bc"

[versions]
fabric = "0.14.7"
minecraft = "1.19"

[options]
acceptable-game-versions = ["1.19"]
