name = "Fabric Modpack"
author = "Laen111"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "22c3d9a4b45760f2dc3b50596b2d0a4058bd04e953c454331612f1385a7ac9a9"

[versions]
fabric = "0.14.7"
minecraft = "1.19"

[options]
acceptable-game-versions = ["1.18.1", "1.18.2", "1.19"]
