name = "Fabric Modpack"
author = "Laen111"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8372df48578076b1a1bc1b3a9d6b0b1de197b21e760a3e7f4dcb5cfeadb7e584"

[versions]
fabric = "0.14.7"
minecraft = "1.19"

[options]
acceptable-game-versions = ["1.19"]
