name = "Fabric Modpack 1.18.2"
author = "Laen111"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ebd6e92255249132d88cbf02f7ba45728ecdb043ab00c5796e2213510d858d3b"

[versions]
fabric = "0.14.7"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18.2"]
