name = "Fabric Modpack 1.19"
author = "Laen111"
version = "1.2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "04c82369cdc23635bfd4cee559b29399f89d73a328c3d4a20cd7cada7407c2b4"

[versions]
fabric = "0.14.7"
minecraft = "1.19"

[options]
acceptable-game-versions = ["1.19"]
